DROP TABLE Has_Restroom CASCADE CONSTRAINTS;
DROP TABLE Has_Parking CASCADE CONSTRAINTS;
DROP TABLE Owns_Equipment_2 CASCADE CONSTRAINTS;
DROP TABLE Has_RentalShop CASCADE CONSTRAINTS;
DROP TABLE Owns_Equipment_1 CASCADE CONSTRAINTS;

DROP TABLE Writes_TrailReview_On CASCADE CONSTRAINTS;
DROP TABLE Explores CASCADE CONSTRAINTS;
DROP TABLE Includes CASCADE CONSTRAINTS;

DROP TABLE PartOf CASCADE CONSTRAINTS;
DROP TABLE Leads_Group CASCADE CONSTRAINTS;
DROP TABLE AppUser CASCADE CONSTRAINTS;

DROP TABLE LocatedIn_Trail_2 CASCADE CONSTRAINTS;
DROP TABLE LocatedIn_Trail_1 CASCADE CONSTRAINTS;

DROP TABLE PartOf_Route_2 CASCADE CONSTRAINTS;
DROP TABLE PartOf_Route_1 CASCADE CONSTRAINTS;

DROP TABLE Region CASCADE CONSTRAINTS;
